global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cache-app-1:8080', 'cache-app-2:8080']

  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis-exporter-1:9121'
          - 'redis-exporter-2:9121'
          - 'redis-exporter-3:9121'
          - 'redis-exporter-4:9121'
          - 'redis-exporter-5:9121'
          - 'redis-exporter-6:9121'

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']
